name: Testing

on: push

jobs:
  test_project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout code
        run: |
            pip install --user django
            cd project_2
            python manage.py test
